server:
  port: 8089
  tomcat:
    accesslog:
      enabled: true
      pattern: common
      suffix: .log
      prefix: accesslog
      file-date-format: .yyyy-MM-dd
      directory: logs
    basedir: .
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root@1234
    #platform: oauth # resource 에 있는 schema.sql 을 실행
    #initialization-mode: always # sql script 자동 실행
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #hibernate:
      #ddl-auto: create
security:
  oauth2:
    authorization:
      token-key-access: isAuthenticated() # key 정보 얻어갈 수 있도록 함.
#security:
#  oauth2:
#    jwt:
#      signKey: 123@#$ signKey 는 토큰을 암호화 복호화 할때 쓰는키로 계속 바뀌니 정의 해 준다. (대칭키로 암호화 할시 사용)