server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root@1234
    #platform: oauth # resource 에 있는 schema.sql 을 실행
    #initialization-mode: always # sql script 자동 실행
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #hibernate:
      #ddl-auto: create